# docker-compose.yml
# https://dev.to/ishankhare07/nginx-as-reverse-proxy-for-a-flask-app-using-docker-3ajg
version: '3'
services: 
  nginx:
    image: nginx:1.13.7
    container_name: nginx
    depends_on:
      - flask
    ports:
        - 80:80
    networks:
        - my-network
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf

  flask:
    image: flask-app
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile_flask
    networks:
      my-network:
          aliases:
              - flask-app
    ports:
      - "8080:5000"
    volumes:
      - "./:/app"
    links:
      - db
 
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: movies
      # MYSQL_USER: movies
      # MYSQL_PASSWORD: movies

networks:
  my-network:
  
  